steps:
  - command: | # Amazon Linux 1 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":aws: Amazon Linux 1 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux1_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: | # Amazon Linux 2 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":aws: Amazon Linux 2 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: | # CentOS 7 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":centos: CentOS 7 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: | # Fedora 27 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":centos: Fedora 27 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:fedora27_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: | # Ubuntu 16.04 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":ubuntu: Ubuntu 16.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: | # Ubuntu 18.04 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":ubuntu: Ubuntu 18.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: | # macOS High Sierra Build
      echo "--- Creating symbolic link to job directory :file_folder:"
      sleep 5
      ln -s "$(pwd)" /data/job
      cd /data/job
      echo "+++ Building :hammer:"
      ./scripts/eosio_build.sh -y
      echo "--- Compressing build directory :compression:"
      tar -pczf build.tar.gz build
      if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":darwin: High Sierra Build"
    agents:
      - "role=builder-v2-1"
      - "os=high-sierra"
    artifact_paths: "build.tar.gz"
    timeout: 60

  - command: | # macOS Mojave Build
      echo "--- Creating symbolic link to job directory :file_folder:"
      sleep 5
      ln -s "$(pwd)" /data/job
      cd /data/job
      echo "+++ Building :hammer:"
      ./scripts/eosio_build.sh -y
      echo "--- Compressing build directory :compression:"
      tar -pczf build.tar.gz build
      if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":darwin: Mojave Build"
    agents:
      - "role=builder-v2-1"
      - "os=mojave"
    artifact_paths: "build.tar.gz"
    timeout: 60

  - wait

  - command: | # Amazon Linux 1 Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Amazon Linux 1 Build"
        echo "+++ :microscope: Running LR Tests"
        ./scripts/long-running-test.sh
    label: ":aws: Amazon Linux 1 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux1_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 90

  - command: | # Amazon Linux 2 Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Amazon Linux 2 Build"
        echo "+++ :microscope: Running LR Tests"
        ./scripts/long-running-test.sh
    label: ":aws: Amazon Linux 2 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 90
    skip: true # fundamental test framework issue here, see https://buildkite.com/EOSIO/eosio/builds/10690

  - command: | # centOS 7 Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: CentOS 7 Build"
        echo "+++ :microscope: Running LR Tests"
        ./scripts/long-running-test.sh
    label: ":centos: CentOS 7 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 90

  - command: | # Fedora 27 Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: Fedora 27 Build"
        echo "+++ :microscope: Running LR Tests"
        ./scripts/long-running-test.sh
    label: ":fedora: Fedora 27 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:fedora27_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 90

  - command: | # Ubuntu 16.04 Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        echo "+++ :microscope: Running LR Tests"
        ./scripts/long-running-test.sh
    label: ":ubuntu: Ubuntu 16.04 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 90
  
  - command: | # Ubuntu 18.04 Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        echo "+++ :microscope: Running LR Tests"
        ./scripts/long-running-test.sh
    label: ":ubuntu: Ubuntu 18.04 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 90

  - command: | # High Sierra Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: High Sierra Build"
        echo "+++ :microscope: Running LR Tests"
        ln -s "$(pwd)" /data/job && ./scripts/long-running-test.sh
    label: ":darwin: High Sierra LR Tests"
    agents:
      - "role=tester-v2-1"
      - "os=high-sierra"
    timeout: 90

  - command: | # Mojave Tests
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build"
        echo "+++ :microscope: Running LR Tests"
        ln -s "$(pwd)" /data/job && ./scripts/long-running-test.sh
    label: ":darwin: Mojave LR Tests"
    agents:
      - "role=tester-v2-1"
      - "os=mojave"
    timeout: 90