#!/bin/sh

set -e
Python_DISTLIB=$(python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))" | sed 's/site-packages/dist-packages/')
mkdir -p $Python_DISTLIB
ln -sf @CMAKE_INSTALL_FULL_DATAROOTDIR@/leap_testing/tests/TestHarness $Python_DISTLIB/TestHarness


# leap_testing is part of the package so should already exist by the time postinst runs
if [ ! -L @CMAKE_INSTALL_FULL_DATAROOTDIR@/leap_testing/bin ]; then
    ln -s ../../bin @CMAKE_INSTALL_FULL_DATAROOTDIR@/leap_testing/bin
fi