#!/bin/sh

# Cleanup symbolic links created during postinst
Python_DISTLIB=$(python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))" | sed 's/site-packages/dist-packages/')
rm -f $Python_DISTLIB/TestHarness
rm -f @CMAKE_INSTALL_FULL_DATAROOTDIR@/leap_testing/bin
