name: Artifacts Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build nodeos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential      \
                             cmake                \
                             curl                 \
                             git                  \
                             jq                   \
                             libboost-all-dev     \
                             libcurl4-openssl-dev \
                             libgmp-dev           \
                             libssl-dev           \
                             llvm-11-dev          \
                             ninja-build          \
                             python3-numpy        \
                             zstdi
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build setup
        run: mkdir build

      - name: Build
        working-directory: ./build
        run: |
          cmake ..
          make -j$(nproc)

      - name: version
        run: echo "::set-output name=version::$(./build/bin/nodeos --version)"
        id: version


