name: Artifacts Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build nodeos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Remove default llvm
        run: sudo apt-get remove -y llvm*
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential      \
                    cmake                \
                    curl                 \
                    git                  \
                    jq                   \
                    libboost-all-dev     \
                    libcurl4-openssl-dev \
                    libgmp-dev           \
                    libssl-dev           \
                    llvm-11-dev          \
                    ninja-build          \
                    python3-numpy        \
                    zstd
          version: 1.0
      - name: Build prep
        run: |
          chown -R $(id -u):$(id -g) $PWD
          mkdir build
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j$(nproc)
        working-directory: ./build
      - name: version
        run: echo "::set-output name=version::$(./build/bin/nodeos --version)"
        id: version


