name: Artifacts Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build nodeos
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Remove default llvm
        run: sudo apt-get remove -y llvm*
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential      \
                    cmake                \
                    curl                 \
                    git                  \
                    jq                   \
                    libboost-all-dev     \
                    libusb-1.0-0-dev     \
                    libcurl4-openssl-dev \
                    libgmp-dev           \
                    libssl-dev           \
                    llvm-11-dev          \
                    ninja-build          \
                    python3-numpy        \
                    zstd
          version: 1.0
      - name: Build prep
        run: |
          chown -R $(id -u):$(id -g) $PWD
          mkdir build
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j$(nproc) package
          ls -la
        working-directory: ./build
      - name: Set version
        id: set_version
        run: |
          echo "version=$(./build/bin/nodeos --version)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/leap*.deb
            ./build/leap*.rpm
            ./build/leap*.tar.gz



