name: Artifacts Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build nodeos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        id: build
        run: |
          sudo apt-get update
          sudo apt-get remove -y llvm*
          sudo apt-get install -y build-essential      \
                                  cmake                \
                                  curl                 \
                                  git                  \
                                  jq                   \
                                  libboost-all-dev     \
                                  libcurl4-openssl-dev \
                                  libgmp-dev           \
                                  libssl-dev           \
                                  llvm-11-dev          \
                                  ninja-build          \
                                  python3-numpy        \
                                  zstd
          chown -R $(id -u):$(id -g) $PWD
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -GNinja ..
          make -j$(nproc)
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: version
        run: echo "::set-output name=version::$(./build/bin/nodeos --version)"
        id: version


