name: "Build leap"

on:
  workflow_call:
    inputs:
      platforms:
        description: "Platforms definitions"
        type: string
        required: true
      platform-list:
        description: "Array of platforms"
        type: string
        required: true

permissions:
  packages: read
  contents: read

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build leap
    strategy:
      fail-fast: false
      matrix:
        platform: ${{fromJSON(inputs.platform-list)}}
    runs-on: ["self-hosted", "enf-x86-beefy"]
    container: ${{fromJSON(inputs.platforms)[matrix.platform].image}}
    steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Build
          id: build
          run: |
            # https://github.com/actions/runner/issues/2033
            chown -R $(id -u):$(id -g) $PWD
            cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_LEAP_DEV_DEB=On ${LEAP_PLATFORM_HAS_EXTRAS_CMAKE:+-C /extras.cmake} -GNinja
            cmake --build build
            tar -pc --exclude "*.o" build | zstd --long -T0 -9 > build.tar.zst
        - name: Upload builddir
          uses: actions/upload-artifact@v4
          with:
            name: ${{matrix.platform}}-build
            path: build.tar.zst
            compression-level: 0