name: "Pinned Build"

on:
  workflow_dispatch:

permissions:
  packages: read
  contents: read

defaults:
  run:
    shell: bash

jobs:
  Temp:
    name: temp
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          pwd
