name: "Pinned Build"

on:
  workflow_dispatch:

permissions:
  packages: read
  contents: read

defaults:
  run:
    shell: bash

jobs:
  d:
    name: Discover Platforms
    runs-on: ubuntu-latest
    outputs:
      missing-platforms: ${{steps.discover.outputs.missing-platforms}}
      p: ${{steps.discover.outputs.platforms}}
    steps:
      - name: Discover Platforms
        id: discover
        uses: AntelopeIO/discover-platforms-action@v1
        with:
          platform-file: .cicd/platforms.json
          password: ${{secrets.GITHUB_TOKEN}}
          package-name: builders

  Build:
    name: Build
    needs: [d]
    if: always() && needs.d.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu20, ubuntu22]
    runs-on: ["self-hosted", "enf-x86-beefy"] # not sure if this warrants a different machine, but start here due to building
    container: ${{ matrix.platform == 'ubuntu20' && 'ubuntu:focal' || 'ubuntu:jammy' }}
    steps:
      - name: Update and Install git
        run: |
          apt-get update
          apt-get install -y git
          git --version
      - name: Clone leap
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
          ./scripts/install_deps.sh
      - name: Build Pinned Build
        run: |
          ./scripts/pinned_build.sh deps build "$(nproc)"
          cd build
          cpack
          ls -l
          cd ..
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: leap-${{matrix.platform}}-amd64
          path: build/leap*.deb
      - name: Run Parallel Tests
        run: |
          cd build
          ctest --output-on-failure -j $(nproc) -LE "(nonparallelizable_tests|long_running_tests)" --timeout 420
