name: Release Actions

on:
  release:
    types: [published]

jobs:
  eb:
    name: experimental-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM scratch
          LABEL org.opencontainers.image.description="A collection of experimental Leap binary packages"
          COPY *.deb /
          EOF
      - name: Get ubuntu20 leap-dev.deb
        uses: AntelopeIO/asset-artifact-download-action@v3
        with:
          owner: ${{github.repository_owner}}
          repo: ${{github.event.repository.name}}
          file: leap-dev.deb
          target: ${{github.sha}}
          artifact-name: leap-dev-ubuntu20-amd64
          wait-for-exact-target-workflow: true
      - name: Get ubuntu22 leap-dev.deb
        uses: AntelopeIO/asset-artifact-download-action@v3
        with:
          owner: ${{github.repository_owner}}
          repo: ${{github.event.repository.name}}
          file: leap-dev.deb
          target: ${{github.sha}}
          artifact-name: leap-dev-ubuntu22-amd64
          wait-for-exact-target-workflow: true
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{github.token}}
      - name: Build and push experimental-binaries
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{github.repository_owner}}/experimental-binaries:${{github.ref_name}}
          context: .
